version: '3'
services:
  message:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime && 
      echo $${TZ} > /etc/timezone &&
      uchat4mq message"
  keyword:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime && 
      echo $${TZ} > /etc/timezone &&
      uchat4mq keyword"
  member_join:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime && 
      echo $${TZ} > /etc/timezone &&
      uchat4mq memberJoin"
  member_quit:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime && 
      echo $${TZ} > /etc/timezone &&
      uchat4mq memberQuit"
  msgext:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime && 
      echo $${TZ} > /etc/timezone &&
      uchat4mq msgext"
