version: '3'
services:
  message:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: ["message"]
  keyword:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: ["keyword"]
  member_join:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: ["memberJoin"]
  member_quit:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: ["memberQuit"]
  msgext:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: ["msgext"]
  private:
    image: edwinlll/uchat4mq:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4mq.yaml:/usr/local/uchat4mq/.uchat4mq.yaml
    command: ["private"]
